name: Backend Pipeline

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - '*'
    inputs:
      name:
        description: 'Deploy Application'
        default: 'World'
        required: false
#  push:
#    branches:
#      - master
#    tags:
#      - '*'


jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"

    - name: Send
      run: echo "branch"

    - name: sleep
      run: sleep 20