name: GCP Secret

on:
  push:
    branches:
      - master

jobs:
  secret:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/google-github-actions/get-secretmanager-secrets
    - name: Get secret
      id: secrets
      uses: google-github-actions/get-secretmanager-secrets@main
      with:
        credentials: ${{ secrets.GCP_SECRET_READER }}
        # output: projects/<project-id>/secrets/<secret-id>
        # gc secrets describe testing
        secrets: |-
          token:projects/844605059718/secrets/testing

    - name: debug output
      id: debug
      run: echo ${{ steps.secrets.outputs.token }} > file.txt

#    - name: debug2
#      id: debug2
#      shell: bash
#      env:
#        SUPER_SECRET: ${{ steps.secrets.outputs.token }}
#      run: |
#        echo "$SUPER_SECRET" > file.txt

    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: file.txt