# Had to add role to service account via cli
# gcloud secrets add-iam-policy-binding testing --member="serviceAccount:github@gcpterraform-866733.iam.gserviceaccount.com" --role="roles/secretmanager.secretAccessor"

name: GCP Secret

on:
  push:
    branches:
      - master

jobs:
  secret:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/google-github-actions/get-secretmanager-secrets
    - name: Get secret
      id: secrets
      uses: google-github-actions/get-secretmanager-secrets@main
      with:
        credentials: ${{ secrets.GCP_SECRET_READER }}
        # output: projects/<project-id>/secrets/<secret-id>
        # gc secrets describe testing
        secrets: |-
          token:projects/844605059718/secrets/testing
          first:projects/844605059718/secrets/testing/versions/1

    - name: debug output
      id: debug
      run: echo ${{ steps.secrets.outputs.token }} > file.txt

    - name: debug output 2
      id: debug2
      run: echo ${{ steps.secrets.outputs.first }} >> file.txt

    - uses: actions/upload-artifact@v2
      with:
        name: file.txt
        path: file.txt