name: GCP Secret

on:
  push:
    branches:
      - master

jobs:
  secret:
    runs-on: ubuntu-latest
    steps:
    - name: debug output
      id: debug2
      run: echo ${{ secrets.GCP_SECRET_READER }}

      # https://github.com/google-github-actions/get-secretmanager-secrets
    - name: Get secret
      id: secrets
      uses: google-github-actions/get-secretmanager-secrets@main
      with:
        credentials: ${{ secrets.GCP_SECRET_READER }}
        # output: projects/<project-id>/secrets/<secret-id>
        # gc secrets describe testing
        secrets: |-
          token:projects/844605059718/secrets/testing

    - name: debug output
      id: debug
      run: echo ${{ steps.secrets.outputs.token }}
