name: One Stop Shop

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    - cron: "0 9 * 1-5 *"
  workflow_dispatch:
    branches:
      - dev
    tags:
      - '*'
    inputs:
      name:
        description: 'Deploy Application'
        default: 'World'
        required: false
#  push:
#    branches:
#      - master
#    tags:
#      - '*'


jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"

  pr-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR list
        uses: leopic/gh-action-open-pr-notifier@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          slackbot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-conversation-id: githubactions_notifications
