name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Deploy Application'
        required: false

jobs:
#  success-notification:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - run: exit 0
#      - name: Slack Success
#        if: always()
#        uses: kpritam/slack-job-status-action@v1
#        with:
#          job-status: ${{ job.status }}
#          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
#          channel: githubactions_notifications
#
#  failure-notification:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - run: exit 1
#      - name: Slack Failure
#        if: always()
#        uses: kpritam/slack-job-status-action@v1
#        with:
#          job-status: ${{ job.status }}
#          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
#          channel: githubactions_notifications

#  notification2:
#    runs-on: ubuntu-latest
#    steps:
#      - name: message1
#        id: message1
#        #if: ${{ failure() }}
#        uses: 8398a7/action-slack@v3
#        with:
#          status: ${{ job.status }}
#          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
#        env:
##          GITHUB_TOKEN: ${{ github.token }} # optional
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required

#  notification3:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Message2
#        id: message2
#        uses: rtCamp/action-slack-notify@master
#        env:
#          SLACK_CHANNEL: githubactions_notifications
#          SLACK_COLOR: '#3278BD'
#          SLACK_ICON: https://github.com/rtCamp.png?size=48
#          SLACK_MESSAGE: 'Post Content :rocket: ${{ github.event.inputs.name }}'
#          SLACK_TITLE: Notification
#          SLACK_USERNAME: something
#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}


  build:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ca-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

#    - name: Checkout repo
#      uses: actions/checkout@v2

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: dev-testing
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build . -t $ECR_REGISTRY/$ECR_REPOSITORY:$(git rev-parse --short=8 ${{ github.sha }})
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$(git rev-parse --short=8 ${{ github.sha }})

    - name: Build failed
      if: ${{ failure() }}
      uses: kpritam/slack-job-status-action@v1
      with:
        job-status: ${{ job.status }}
        slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
        channel: githubactions_notifications

    - name: Build completed
      if: ${{ success() }}
      uses: kpritam/slack-job-status-action@v1
      with:
        job-status: ${{ job.status }}
        slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
        channel: githubactions_notifications



