name: One Stop Shop

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    - cron: "0 9 * 1-5 *"
  workflow_dispatch:
    branches:
      - dev
    tags:
      - '*'
    inputs:
      name:
        description: 'Deploy Application'
        default: 'World'
        required: false
#  push:
#    branches:
#      - master
#    tags:
#      - '*'


jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"

  pr-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR list
        uses: leopic/gh-action-open-pr-notifier@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          slackbot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-conversation-id: githubactions_notifications


  pr-monitor-job:
    runs-on: ubuntu-latest
    name: PR monitor
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Scan for PRs
        id: scan
        uses: andrewandante/pr-monitor-slack-action@v1.0.0
        with:
          # required inputs
          slack-token: ${{ secrets.SLACK_BOT_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # optional inputs (with defaults set)
          channel: '#githubactions_notifications'
          sort: 'updated'
          sort-direction: 'desc'
          approved-emoji: 'heavy_check_mark'
          pending-emoji: 'heavy_minus_sign'
          changes-requested-emoji: 'x'
          requested-reviewer-emoji: 'heavy_minus_sign'
