name: One Stop Shop

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
    inputs:
      name:
        description: 'Deploy Application'
        default: 'World'
        required: false
#  push:
#    branches:
#      - master
#    tags:
#      - '*'
##  pull_request:
##    types: [opened, ready_for_review]
##  pull_request_review:
##    types: [submitted]

jobs:
  notifications:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"

    - name: sleep 30
      run: sleep 30
