name: End 2 End

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_run:
    workflows: ["Frontend Pipeline" && "Backend Pipeline"]
    types:
      - completed
    inputs:
      name:
        description: 'Deploy Application'
        default: 'World'
        required: false
#  push:
#    branches:
#      - master
#    tags:
#      - '*'


jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
